### ISSUE TITLE
Uncaught Exception: Error: Object has been destroyed

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zecwallet#252]
Latest master.

Steps:
1. `yarn dev`
2. As soon as the dock icon appears, right click -> Quit
3. Just before the app starts quitting, select any item from the menu bar.

What happened:
Exception is thrown.
```
Uncaught Exception:
Error: Object has been destroyed
    at click (/Users/rex/zecwallet/app/menu.js:125:29)
    at MenuItem.click (electron/js2c/browser_init.js:1516:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1777:13)
```

Expected result:
No exception.

**Comment by rex4539** [comment]
Also very easy to reproduce with the following steps:
1. `yarn dev`
2. As soon as the main window appears, press Cmd+Q and immediately click on the menu bar.
3. Select any item.

**Comment by rex4539** [comment]
Applicable to Zecwallet Lite too.

```
Uncaught Exception:
Error: Object has been destroyed
    at click (/Users/rex/zecwallet-lite/app/menu.js:50:24)
    at MenuItem.click (electron/js2c/browser_init.js:1516:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1777:13)
```
