### ISSUE TITLE
Version 1.8.1 does not start on macos

### ISSUE THREAD

**Issue by lukaszsamson** [ZcashFoundation/zecwallet#370]
Is this a bug report?
Yes
If so, go back and select the "Bug report" option or your issue WILL be closed.
I'd love to but the issue template selection is broken. It only has Feature request

Error description:

UI error
```
Error: Error invoking remote method 'doRPC_IPC': NO_CONNECTION
```

Electron console logs

```
Cannot start zcashd because it is not supported yet
```

<img width="1203" alt="Screenshot 2022-07-15 at 09 54 22" src="https://user-images.githubusercontent.com/1078186/179178675-3d899894-39c7-4728-a1d9-996df6f4c8c8.png">

**Comment by adityapk00** [comment]
You need to start zcashd manually in a terminal window and wait for it to sync. `zcashd` for MacOS is included in the distribution

**Comment by lukaszsamson** [comment]
> You need to start zcashd manually in a terminal window and wait for it to sync. zcashd for MacOS is included in the distribution

@adityapk00 that's not a nice user experience. It's not trivial to find the binaries in package content in Applications

Anyway it is still broken after syncing manually. The error is the same as before. It seems zecwallet is unable to start zcash.

Even if I keep zcashd running in terminal it's still not working correctly. It is unable to load my testnet wallet (that used to work before 5.0.0 had fork)

<img width="1195" alt="Screenshot 2022-07-16 at 10 15 40" src="https://user-images.githubusercontent.com/1078186/179346723-cbd5a404-f7f7-44a8-a031-c69e6044e029.png">
running `zcashd-wallet-tool` and restarting does not help - the same error is still displayed


Clicking anywhere in the UI (receive, address book) crashes the javascript
receive
<img width="1190" alt="Screenshot 2022-07-16 at 10 18 17" src="https://user-images.githubusercontent.com/1078186/179346821-0d5368c0-2ee6-4312-873e-2943f77959af.png">
```
TypeError: a.reduce is not a function
    at wc.render (Receive.tsx:340:40)
    at Ps (react-dom.production.min.js:204:189)
    at Os (react-dom.production.min.js:203:149)
    at Cl (react-dom.production.min.js:292:172)
    at bu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at ou (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Va (react-dom.production.min.js:127:105)
```
address book
<img width="1195" alt="Screenshot 2022-07-16 at 10 29 59" src="https://user-images.githubusercontent.com/1078186/179347227-5e1d3088-05b8-4bcd-95dc-d126a775cb6d.png">

```
TypeError: n.find is not a function
    at sd.validate (Addressbook.tsx:146:34)
    at sd.render (Addressbook.tsx:163:49)
    at Ps (react-dom.production.min.js:204:189)
    at Os (react-dom.production.min.js:203:149)
    at Cl (react-dom.production.min.js:292:172)
    at bu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at ou (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
```

**Comment by morein22** [comment]
Indeed, same problems on limux.
